# Generated by Django 3.0 on 2022-07-19 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0018_auto_20220718_0719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_question',
            old_name='student',
            new_name='applicant',
        ),
        migrations.RenameField(
            model_name='employeeexam_db',
            old_name='user',
            new_name='applicant',
        ),
        migrations.RenameField(
            model_name='employeeresults_db',
            old_name='user',
            new_name='applicant',
        ),
        migrations.RenameField(
            model_name='exam_model',
            old_name='user',
            new_name='employer',
        ),
        migrations.RenameField(
            model_name='question_db',
            old_name='user',
            new_name='employer',
        ),
        migrations.RenameField(
            model_name='question_paper',
            old_name='user',
            new_name='employer',
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 3, 31, 17, 122532)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 3, 31, 17, 122532)),
        ),
    ]
